return unique subscriptions in GetSubscriptionsData() method
opdev/opcap pull request #172
Opened 2022-08-23 19:04 UTC by OchiengEd

Update the `GetSubscriptionsData()` method to return uniquely named subscriptions for each of the install modes supported by an operator.

In addition, refactor the in preparation for testing of all install modes supported
by an operator.

Closes #167

Signed-off-by: Edmund Ochieng <ochienged@gmail.com>

2022-08-23 19:40 UTC, yashoza19 approved these changes
/approve

2022-08-23 19:54 UTC, acmenezes requested changes
Everything looks perfect. I just have a simple question that would like to answer before merging. How does this change affect a full run? How long does it take to finish? I want to make sure we can do it in timely manner or be able to choose one installMode when needed to run all fast.

2022-08-24 13:15 UTC, OchiengEd commented
This was not trying to solve that but to ensure all the data needed to create unique subscriptions for each supported install plan is created. Previously, all install plans would have the same name.

The next batch of work would look specifically into the implementation of testing all the install modes.

2022-08-24 13:28 UTC, acmenezes commented
> The next batch of work would look specifically into the implementation of testing all the install modes.

@OchiengEd , so it doesn't change the run time, right? That's what I was trying to understand.

2022-08-25 16:43 UTC, OchiengEd commented
Closing this PR and will merge with any other work needed to allow the testing of all supported install modes. This is otherwise going to block me.

2022-08-25 16:43 UTC, closed without merging