Simplify and refactor cmd/ package
opdev/opcap pull request #179
Opened 2022-08-26 20:29 UTC by bcrochet

* Send the same context down from main
* Move upload to an internal package
* Get rid of init()'s in cmd/
* Add tests for cmd/ package
* Take out redundant text from check long description

Signed-off-by: Brad P. Crochet <brad@redhat.com>

2022-08-29 13:56 UTC, acmenezes requested changes
Hi @bcrochet thanks a lot for doing this! I review it carefully but one first thing I would ask is: do you have an issue for that? Could please open one? I would like to give people the chance to discuss the issues before pushing PRs. Otherwise we'll have some trouble tracking everything.

2022-08-29 14:03 UTC, mrhillsman commented
/hold

2022-08-30 12:29 UTC, bcrochet commented
> Hi @bcrochet thanks a lot for doing this! I review it carefully but one first thing I would ask is: do you have an issue for that? Could please open one? I would like to give people the chance to discuss the issues before pushing PRs. Otherwise we'll have some trouble tracking everything.

Sure. I can open one.

2022-08-30 12:40 UTC, bcrochet commented
Would you prefer that I split this one up a bit? It might make it easier to consume that way.

2022-08-30 14:31 UTC, closed without merging