Support all-installmodes tests for an operator
opdev/opcap pull request #196
Opened 2022-09-04 00:50 UTC by yashoza19

## Description of PR
This commit allows the testing of all install modes that are supported
by an operator.
Fixes #189.

## Changes (required)

- [add all-install modes flag to check command](https://github.com/opdev/opcap/commit/222300d71a5871dcb6db46c825c04500ab329812)
- [add all install mode types to SubscriptionList](https://github.com/opdev/opcap/commit/de280cf71c6a1264c7c07664101f8b5abf1ef7ee)
- [add logic to the auditor to support testing all install modes by an operator](https://github.com/opdev/opcap/commit/409dc97f82b1694ed92607ced49351d814dce15e)

## Checklist (required)

- [x] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if needed
- [x] I have checked that my changes pass all tests

Signed-off-by: Yash Oza <yoza@redhat.com>

2022-09-06 18:30 UTC, bcrochet requested changes
A comment and a change.

2022-09-06 18:30 UTC, bcrochet commented on internal/capability/audit.go
> +	ns := strings.Join([]string{"opcap", strings.ReplaceAll(subscription.Package, ".", "-"), strings.ToLower(string(subscription.InstallModeType))}, "-")
Please remove the newline before this.

2022-09-06 18:42 UTC, bcrochet approved these changes
/lgtm

2022-09-07 18:11 UTC, acmenezes approved these changes
Looks good! Thanks! One single comment to keep in mind, seems to me that we could consider using the word audit all install modes in place of test. Because we'll get confused sometime when speaking about tests. Since we're beginning to ramp up with actual code testing. But this is just for future PRs to make things a bit clear. Again, thanks!

2022-09-07 18:47 UTC, acmenezes commented
/lgtm

2022-09-07 18:47 UTC, merged