refactor unit tests for namespace and operatorGroup
opdev/opcap pull request #244
Opened 2022-09-21 03:19 UTC by yashoza19

## Description of PR
Fixes #243.

## Changes (required)

- namespace_test.go
- operator_group_test.go

## Checklist (required)
- [x] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if needed
- [x] I have checked that my changes pass all tests

Signed-off-by: yoza <yoza@redhat.com>

2022-09-21 15:31 UTC, acmenezes approved these changes
That looks great!

2022-09-22 16:26 UTC, skattoju approved these changes
/lgtm

2022-09-22 16:27 UTC, bcrochet requested changes
🛑  A few changes

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
>  	}
This code needs to be in a BeforeEach()

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
> +			ns, err := operatorClient.CreateNamespace(context.TODO(), "testns")
This should be inside the It()

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				It("should error", func() {
This should not be inside the JustBeforeEach

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
>  				ns, err := operatorClient.CreateNamespace(context.TODO(), "testns")
This line should be in both the JustBeforeEach, and in the It()

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
> +			err := operatorClient.DeleteNamespace(context.TODO(), "testns")
This should be inside the It()

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				err := operatorClient.DeleteNamespace(context.TODO(), "testns")
Same as the Create

2022-09-22 16:27 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +	operatorGroupData := OperatorGroupData{
Generally same comments as NameSpace.

2022-09-22 16:27 UTC, merged