refactor unit tests for namespace and operator group
opdev/opcap pull request #245
Opened 2022-09-22 18:57 UTC by yashoza19

## Description of PR
Fixes #243 

## Checklist (required)
- [x] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation if needed
- [x] I have checked that my changes pass all tests

2022-09-22 19:07 UTC, bcrochet requested changes
A few more suggestions.

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				operatorClient.CreateNamespace(context.TODO(), "testns")
```suggestion
				_, err := operatorClient.CreateNamespace(context.TODO(), "testns")
				Expect(err).ToNot(HaveOccurred())
```

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +	var operatorGroupData OperatorGroupData
Same as the namespace. Just leave the vars out of the BeforeEach. Everything else in.

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +				operatorClient.CreateOperatorGroup(context.TODO(), operatorGroupData, "testns")
Ditto

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/namespace_test.go
>  			It("should succeed", func() {
You need to create the namespace here, so you have something to delete.

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				operatorClient.DeleteNamespace(context.TODO(), "testns")
This is unnecessary.

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				Expect(err).To(MatchError("could not delete namespace: testns: namespaces \"testns\" not found"))
I don't think we care _what_ the error is, just that it happens. Instead, I would just wrap the previous line in 

```
Expect(...).To(HaveOccurred())
```

2022-09-22 19:07 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +	var operatorGroupData OperatorGroupData
In fact, pretty much all of my comments there apply here.

2022-09-22 19:24 UTC, bcrochet approved these changes
/lgtm

2022-09-23 14:23 UTC, bcrochet commented on internal/operator/namespace_test.go
> +				Expect(operatorClient.DeleteNamespace(context.TODO(), "testns")).To(HaveOccurred())
Nit: Would read better as ToNot(Succeed())

2022-09-23 14:23 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +				Expect(operatorClient.DeleteOperatorGroup(context.TODO(), "testog", "testns")).ToNot(HaveOccurred())
Ditto.

2022-09-23 14:23 UTC, bcrochet commented on internal/operator/operator_group_test.go
> +				Expect(operatorClient.DeleteOperatorGroup(context.TODO(), "testog", "testns")).To(HaveOccurred())
Ditto

2022-09-23 19:53 UTC, bcrochet approved these changes
/lgtm

2022-09-26 15:32 UTC, acmenezes approved these changes
/approve

2022-09-26 15:33 UTC, merged