Truncate namespace when generated
opdev/opcap pull request #272
Opened 2022-10-10 18:22 UTC by bcrochet

## Description of PR

Namespaces cannot be over 63 characters. Some package names are long enough that when "opcap-" and the install mode are added, the namespace if no longer valid.

Fixes #271

Signed-off-by: Brad P. Crochet <brad@redhat.com>

## Changes (required)

* Add unit test for audit namespace
* Add fake client
* Add namespace generator function

## Checklist (required)
- [X] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation if needed
- [X] I have checked that my changes pass all tests

2022-10-10 18:53 UTC, yashoza19 approved these changes
/approve

2022-10-13 13:50 UTC, mrhillsman requested changes
suite_test.go changes are not related namespace truncating

2022-10-13 13:51 UTC, mrhillsman commented
/remove approve

2022-10-13 13:51 UTC, mrhillsman commented
/remove-approve

2022-10-13 13:52 UTC, mrhillsman commented
/unapprove

2022-10-13 22:07 UTC, bcrochet commented
> suite_test.go changes are not related namespace truncating

If you look closer, you see that the test in audit_test.go uses fakeOpClient.

2022-10-14 13:59 UTC, bcrochet commented
> > suite_test.go changes are not related namespace truncating
> 
> If you look closer, you see that the test in audit_test.go uses fakeOpClient.
> 
> https://github.com/opdev/opcap/pull/272/files#diff-ab1655423e7300f688424dbbb24d3bd3a5b054bb367b88f9b300dbda04078267R22

Actually, I'll change it to what I did in #275. It's a cleaner impl.

2022-10-14 14:28 UTC, mrhillsman commented
@bcrochet I guess the only concern than is if this PR for some strange reason needs to be touched do the changes to suite_test still need to be around?

2022-10-14 14:32 UTC, skattoju commented on internal/capability/audit.go
> +	namespaceLength := 63 - len("opcap-") - len(installModeString) - 1
neat!

2022-10-14 14:33 UTC, skattoju approved these changes

2022-10-14 16:01 UTC, mrhillsman approved these changes

2022-10-14 16:02 UTC, merged