Add an option to pass an io.Writer to audits
opdev/opcap pull request #303
Opened 2022-10-25 15:31 UTC by bcrochet

## Description of PR
To make audits easier to test, pass in an io.Writer to be used for writing the text reports. This will allow the writer to be changed out with a buffer for instance so it can be validated in a test without writing directly to stdout.

Signed-off-by: Brad P. Crochet <brad@redhat.com>

Fixes #299

## Changes (required)

- Add an option for passing an io.Writer to audits
- Pass the cmd.OutOrStdout to RunAudits 

## Checklist (required)
- [X] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation if needed
- [X] I have checked that my changes pass all tests

2022-10-27 20:17 UTC, skattoju approved these changes
/lgtm

2022-10-27 21:32 UTC, acmenezes requested changes
Looking at this one and the previous one with the afero file system I believe we could stick only with a generic io.Writter and use afero as another io.Writer. Is it possible? Like with the os.File one?

2022-10-28 13:00 UTC, bcrochet commented
> Looking at this one and the previous one with the afero file system I believe we could stick only with a generic io.Writter and use afero as another io.Writer. Is it possible? Like with the os.File one?

Let me look at how that might work...

2022-10-28 13:06 UTC, bcrochet commented
> Looking at this one and the previous one with the afero file system I believe we could stick only with a generic io.Writter and use afero as another io.Writer. Is it possible? Like with the os.File one?

I'd say let's maybe take care of that after @skattoju is done with his work on the reports.

2022-10-28 14:50 UTC, acmenezes commented
/approve

2022-10-28 15:52 UTC, yashoza19 reviewed
/lgtm

2022-10-28 15:54 UTC, merged