Couple of changes to fix logs
opdev/opcap pull request #60
Opened 2022-06-09 16:23 UTC by yashoza19

- Changing logs to be printed with (level)w instead of (level)f - Closes #57 
- Changing the path to store logs - Closes #58 

Signed-off-by: Yash Oza <yoyashoza@gmail.com>

2022-06-09 18:10 UTC, mrhillsman commented on .gitignore
> +/std_*.json
Remove _

2022-06-09 18:32 UTC, mrhillsman commented on internal/capability/operator_install.go
> +	logger.Debugw("Installing Pacakge", s.Package, "Channel", s.Channel, "InstallMode", s.InstallModeType)
Pacakge should be Package

2022-06-09 18:38 UTC, mrhillsman requested changes
I left a few comments but after going through it is better to leave overall comment. So the format for using (Level)w is:

```go
(msg string, keysAndValues ...interface{})
```

Some of the uses of Errorw for example are not following this format. If you only want to have a message provided concatenate err to string or use (Level)f as before; i.e. you do not want to add any additional keys to the log object you just want to provide a value to the message key.

2022-06-09 20:18 UTC, mrhillsman commented on internal/capability/operator_install.go
> +			logger.Errorw("Package", subscription.Package, "channel", subscription.Channel, "install mode", subscription.InstallModeType)
Errorw signature is (msg string, keysAndValues ...interface{}). A message is needed and the key/value pairs should be lowercase with no spaces; package vs Package and installmode vs install mode

2022-06-09 20:21 UTC, mrhillsman commented on internal/capability/operator_install.go
> +		logger.Debugw("Error creating subscriptions: %w", err)
Should be Debugf vs Debugw?

2022-06-09 20:21 UTC, mrhillsman commented on internal/operator/client.go
> +		logger.Errorf("Unable to build config from flags", err)
String format error

2022-06-09 20:23 UTC, mrhillsman commented on internal/operator/install_plan.go
> +		logger.Debugw("InstallPlan Approved", installPlan.ObjectMeta.Name, "Namespace", namespace)
Debugw format (msg string, keysAndValues ...interface{}); installPlan.ObjectMeta.Name needs a key, "Namespace" should be "namespace"

2022-06-09 20:23 UTC, mrhillsman commented on internal/operator/install_plan.go
> +			logger.Errorw("Error", err)
Errorf?

2022-06-09 20:24 UTC, mrhillsman commented on internal/operator/namespace.go
> +	logger.Debugw("Namespace Created", name)
Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

2022-06-09 20:24 UTC, mrhillsman commented on internal/operator/namespace.go
> +	logger.Debugw("Delete namespace", name)
Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

2022-06-09 20:24 UTC, mrhillsman commented on internal/operator/namespace.go
> +	logger.Debugw("Namespace Deleted", name)
Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

2022-06-09 20:25 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("Creating OperatorGroup", data.Name, "Namespace", namespace)
Debugw need to fix format; (msg string, keysAndValues ...interface{})
logger.Debugw("Creating OperatorGroup", "operatorgroup", data.Name, "namespace", namespace)?

2022-06-09 20:25 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("OperatorGroup created", data.Name, "Namespace", namespace)
Same as previous comment.

2022-06-09 20:26 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("Deleting OperatorGroup", name, "Namespace", namespace)
Same as previous comment.

2022-06-09 20:26 UTC, mrhillsman commented on internal/operator/secret.go
> +	logger.Debugw("Secret created", name, "Namespace", namespace)
Similar to previous comment.

2022-06-09 20:27 UTC, mrhillsman commented on internal/operator/secret.go
> +	logger.Debugw("Deleting secret", name, "Namespace", namespace)
Similar to previous comment.

2022-06-09 20:27 UTC, mrhillsman commented on internal/operator/subscription.go
> +		logger.Errorw("Error while creating new PackageServerClient", err)
Errorf instead of Errorw? If Errorw need to fix format; logger.Errorw("Error while creating new PackageServerClient", "error", err)

2022-06-09 20:27 UTC, mrhillsman commented on internal/operator/subscription.go
> +		logger.Errorw("Error while listing new PackageManifest Objects", err)
Errorf instead of Errorw? If Errorw need to fix format; logger.Errorw("Error while creating new PackageServerClient", "error", err)

2022-06-09 20:28 UTC, mrhillsman requested changes
I've left comments throughout. Some examples as well of ways to resolve; do not have to be followed exactly as provided.

2022-06-10 14:01 UTC, mrhillsman requested changes

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debug("creating OperatorGroup", "operatorGroup", data.Name, "namespace", namespace)
Debug should be Debugw
operatorGroup should be operatorgroup (currently the standard is all lowercase for key names); unless we want to change this which would require other changes.

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("OperatorGroup created", "operatorGroup", data.Name, "Namespace", namespace)
operatorGroup should be operatorgroup
Namespace should namespace

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("Deleting OperatorGroup", "operatorGroup", name, "Namespace", namespace)
operatorGroup should be operatorgroup
Namespace should namespace

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/operator_group.go
> +	logger.Debugw("OperatorGroup deleted", "operatorGroup", name, "Namespace", namespace)
operatorGroup should be operatorgroup
Namespace should namespace

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/secret.go
> +	logger.Debugw("secret created", "secret", name, "Namespace", namespace)
Namespace should namespace

2022-06-10 14:01 UTC, mrhillsman commented on internal/operator/secret.go
> +	logger.Debugw("deleting secret", "secret", name, "Namespace", namespace)
Namespace should namespace

2022-06-10 14:16 UTC, mrhillsman approved these changes
/lgtm

2022-06-10 14:17 UTC, merged

2022-06-17 18:06 UTC, skattoju commented
fixed #58